"""db 1.1

Revision ID: 296e35daee8b
Revises: 75138516c020
Create Date: 2024-11-04 23:04:35.600396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296e35daee8b'
down_revision = '75138516c020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=12), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
