"""db 1.6

Revision ID: 40118be3234f
Revises: ae84b683c5c7
Create Date: 2024-11-07 19:30:48.463504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40118be3234f'
down_revision = 'ae84b683c5c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaksi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaksi_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_transaksi', sa.Integer(), nullable=True),
    sa.Column('id_menu', sa.Integer(), nullable=True),
    sa.Column('jumlah', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaksi_menu')
    op.drop_table('transaksi')
    # ### end Alembic commands ###
