"""db 1.3

Revision ID: 568ce73288a6
Revises: aee8826cd311
Create Date: 2024-11-05 02:09:32.020750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568ce73288a6'
down_revision = 'aee8826cd311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=42), nullable=True),
    sa.Column('harga', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coffe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coffe_nama'), ['nama'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coffe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coffe_nama'))

    op.drop_table('coffe')
    # ### end Alembic commands ###
